### ISSUE TITLE
notifications fails to start

### ISSUE THREAD

**Issue by trevorwhitney** [cloudfoundry-incubator/notifications-release#26]
We go this error when the CF pushed notifications app tries to start:

```   
2018-02-14T15:30:03.47-0700 [APP/PROC/WEB/1] OUT {"timestamp":"1518647403.477984667","source":"notifications","message":"notifications.crash","log_level":3,"data":{"error":"dial tcp 10.0.16.10:3306: getsockopt: connection refused","trace":"goroutine 1 [running]:\ngithub.com/cloudfoundry-incubator/notifications/vendor/github.com/pivotal-golang/lager.(*logger).Fatal(0xc42001dbc0, 0x55f5eb523206, 0x5, 0x55f5ebb326e0, 0xc42001f810, 0x0, 0x0, 0x0)\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/vendor/github.com/pivotal-golang/lager/logger.go:131 +0xcc\ngithub.com/cloudfoundry-incubator/notifications/application.Application.Crash(0xc4200140c8, 0x2e, 0x55f5eb83b252, 0x1, 0x0, 0x5, 0xc42001e690, 0x4d, 0xc42001a013, 0xa7, ...)\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/application.go:175 +0x129\npanic(0x55f5eb883860, 0xc42001f810)\n\t/tmp/contents665693713/deps/0/go1.8.7/go/src/runtime/panic.go:489 +0x2d3\ngithub.com/cloudfoundry-incubator/notifications/application.(*Mother).SQLDatabase(0xc42012e000, 0x0)\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/mother.go:89 +0x178\ngithub.com/cloudfoundry-incubator/notifications/postal.Boot(0x55f5ebb3b4e0, 0xc42012e000, 0xc42000c20e, 0xd, 0xc420016102, 0x14, 0xc42014a240, 0xc420014049, 0x2e, 0x0, ...)\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/postal/boot.go:65 +0x2f5\ngithub.com/cloudfoundry-incubator/notifications/application.Application.StartWorkers(0xc4200140c8, 0x2e, 0x55f5eb83b252, 0x1, 0x0, 0x5, 0xc42001e690, 0x4d, 0xc42001a013, 0xa7, ...)\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/application.go:134 +0x1ed\ngithub.com/cloudfoundry-incubator/notifications/application.Application.Boot(0xc4200140c8, 0x2e, 0x55f5eb83b252, 0x1, 0x0, 0x5, 0xc42001e690, 0x4d, 0xc42001a013, 0xa7, ...)\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/application.go:58 +0x973\nmain.main()\n\t/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/main.go:19 +0x211\n"}}
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR panic: dial tcp 10.0.16.10:3306: getsockopt: connection refused [recovered]
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	panic: dial tcp 10.0.16.10:3306: getsockopt: connection refused
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR goroutine 1 [running]:
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR github.com/cloudfoundry-incubator/notifications/vendor/github.com/pivotal-golang/lager.(*logger).Fatal(0xc42001dbc0, 0x55f5eb523206, 0x5, 0x55f5ebb326e0, 0xc42001f810, 0x0, 0x0, 0x0)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/vendor/github.com/pivotal-golang/lager/logger.go:152 +0x460
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR github.com/cloudfoundry-incubator/notifications/application.Application.Crash(0xc4200140c8, 0x2e, 0x55f5eb83b252, 0x1, 0x0, 0x5, 0xc42001e690, 0x4d, 0xc42001a013, 0xa7, ...)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/application.go:175 +0x129
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR panic(0x55f5eb883860, 0xc42001f810)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/contents665693713/deps/0/go1.8.7/go/src/runtime/panic.go:489 +0x2d3
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR github.com/cloudfoundry-incubator/notifications/application.(*Mother).SQLDatabase(0xc42012e000, 0x0)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/mother.go:89 +0x178
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR github.com/cloudfoundry-incubator/notifications/postal.Boot(0x55f5ebb3b4e0, 0xc42012e000, 0xc42000c20e, 0xd, 0xc420016102, 0x14, 0xc42014a240, 0xc420014049, 0x2e, 0x0, ...)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/postal/boot.go:65 +0x2f5
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR github.com/cloudfoundry-incubator/notifications/application.Application.StartWorkers(0xc4200140c8, 0x2e, 0x55f5eb83b252, 0x1, 0x0, 0x5, 0xc42001e690, 0x4d, 0xc42001a013, 0xa7, ...)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/application.go:134 +0x1ed
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR github.com/cloudfoundry-incubator/notifications/application.Application.Boot(0xc4200140c8, 0x2e, 0x55f5eb83b252, 0x1, 0x0, 0x5, 0xc42001e690, 0x4d, 0xc42001a013, 0xa7, ...)
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/application/application.go:58 +0x973
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR main.main()
   2018-02-14T15:30:03.48-0700 [APP/PROC/WEB/1] ERR 	/tmp/gobuildpack.gopath766780519/.go/src/github.com/cloudfoundry-incubator/notifications/main.go:19 +0x211
```

The IP it is trying to access is for the singleton-blobstore in the CF release, which appears to be returning a connection refused on port `3306`:
```
singleton-blobstore/8b490226-24d5-42be-a1c6-751fab272471  running        z1  10.0.16.10  vm-bf3f1980-d0c4-4a30-4e28-7848eaf20726  small
```

**Comment by wfernandes** [comment]
@trevorwhitney Thanks for creating this issue. If you have the information, can you please specify the stemcell version being used, notifications-release SHA and cf-deployment SHA.

**Comment by robertjsullivan** [comment]
stemcell is bosh-google-kvm-ubuntu-trusty-go_agent/3541.4

cf-deployment is latest master. 

notifications-release is notifications/44

**Comment by robertjsullivan** [comment]
latest failure is:
Using environment 'https://35.196.76.134:25555' as client 'admin'

Using deployment 'notifications'

Task 39801

Task 39801 | 10:09:10 | Preparing deployment: Preparing deployment
Task 39801 | 10:09:10 | Warning: Ambiguous request: the requested errand name 'deploy-notifications' matches both a job name and an errand instance group name. Executing errand on all relevant instances with job 'deploy-notifications'.
Task 39801 | 10:09:11 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 39801 | 10:09:11 | Preparing deployment: Preparing deployment (00:00:01)
Task 39801 | 10:09:11 | Creating missing vms: deploy-notifications/83a2b600-0ac4-45a8-ad86-ba4e77b1b9ae (0) (00:00:40)
Task 39801 | 10:09:51 | Updating instance deploy-notifications: deploy-notifications/83a2b600-0ac4-45a8-ad86-ba4e77b1b9ae (0) (00:04:25)
Task 39801 | 10:14:16 | Running errand: deploy-notifications/83a2b600-0ac4-45a8-ad86-ba4e77b1b9ae (0) (00:01:05)
Task 39801 | 10:15:21 | Fetching logs for deploy-notifications/83a2b600-0ac4-45a8-ad86-ba4e77b1b9ae (0): Finding and packing log files (00:00:01)

Task 39801 Started  Fri Feb 16 10:09:10 UTC 2018
Task 39801 Finished Fri Feb 16 10:15:22 UTC 2018
Task 39801 Duration 00:06:12
Task 39801 done

Instance   deploy-notifications/83a2b600-0ac4-45a8-ad86-ba4e77b1b9ae  
Exit Code  1  
Stdout     cf version 6.31.0+b35df905d.2017-09-15  
           Setting api endpoint to https://api.cf.healthwatch.gcp.pcf-metrics.com...  
           OK  
             
           api endpoint:   https://api.cf.healthwatch.gcp.pcf-metrics.com  
           api version:    2.103.0  
           Not logged in. Use 'cf login' to log in.  
           API endpoint: https://api.cf.healthwatch.gcp.pcf-metrics.com  
           Authenticating...  
           OK  
           Use 'cf target' to view or set your target org and space.  
           Creating org system as admin...  
           OK  
           Org system already exists  
           api endpoint:   https://api.cf.healthwatch.gcp.pcf-metrics.com  
           api version:    2.103.0  
           user:           admin  
           org:            system  
           No space targeted, use 'cf target -s SPACE'  
           Creating space notifications-service in org system as admin...  
           OK  
           Space notifications-service already exists  
           api endpoint:   https://api.cf.healthwatch.gcp.pcf-metrics.com  
           api version:    2.103.0  
           user:           admin  
           org:            system  
           space:          notifications-service  
           ---  
             
           applications:  
             - name: notifications  
               command: bin/notifications  
               memory: 64M  
               domain: "cf.healthwatch.gcp.pcf-metrics.com"  
               host: notifications  
               diego: true  
                 
           env:  
             CC_HOST: https://api.cf.healthwatch.gcp.pcf-metrics.com  
             DATABASE_URL: "mysql://notifications:notifications@10.0.16.10:3306/notifications"  
             DB_MAX_OPEN_CONNS: "5"  
             DEFAULT_UAA_SCOPES: "cloud_controller.read,cloud_controller.write,openid,approvals.me,cloud_controller_service_permissions.read,scim.me,uaa.user,password.write,scim.userids,oauth.approvals"  
             DOMAIN: "cf.healthwatch.gcp.pcf-metrics.com"  
             ENCRYPTION_KEY: "moons_of_endor"  
             ROOT_PATH: "$HOME"  
             SENDER: "notifications@cf.healthwatch.gcp.pcf-metrics.com"  
             SMTP_AUTH_MECHANISM: "plain"  
             SMTP_CRAMMD5_SECRET: ""  
             SMTP_HOST: "smtp.sendgrid.net"  
             SMTP_PASS: "OMEjUHuj3EK26plz"  
             SMTP_PORT: "2525"  
             SMTP_TLS: "true"  
             SMTP_USER: "pcf-metrics"  
             UAA_CLIENT_ID: "notifications"  
             UAA_CLIENT_SECRET: "notifications-secret"  
             UAA_HOST: https://uaa.cf.healthwatch.gcp.pcf-metrics.com  
             VERIFY_SSL: "false"  
           ebace9fb-d3cf-4cc3-aade-7859fc63f7ce  
           Scaling app notifications in org system / space notifications-service as admin...  
           OK  
           ebace9fb-d3cf-4cc3-aade-7859fc63f7ce  
           Attention: Plugins are binaries written by potentially untrusted authors.  
           Install and use plugins at your own risk.  
           Installing plugin autopilot...  
           OK  
           Plugin autopilot 0.0.2 successfully installed.  
           Renaming app notifications to notifications-venerable in org system / space notifications-service as admin...  
           OK  
           Using manifest file manifest.yml  
             
           Creating app notifications in org system / space notifications-service as admin...  
           OK  
             
           Using route notifications.cf.healthwatch.gcp.pcf-metrics.com  
           Binding notifications.cf.healthwatch.gcp.pcf-metrics.com to notifications...  
           OK  
             
           Uploading notifications...  
           Uploading app files from: /var/vcap/data/packages/notifications/9c0f9613c6e4c732290c66de6218506b98a88554  
           Uploading 899.4K, 1024 files  
                                        Done uploading  
           OK  
             
           Starting app notifications in org system / space notifications-service as admin...  
           Downloading binary_buildpack...  
           Downloading dotnet_core_buildpack...  
           Downloading java_buildpack...  
           Downloading ruby_buildpack...  
           Downloading go_buildpack...  
           Downloaded binary_buildpack  
           Downloaded java_buildpack  
           Downloaded go_buildpack  
           Downloading nodejs_buildpack...  
           Downloading python_buildpack...  
           Downloaded ruby_buildpack  
           Downloading php_buildpack...  
           Downloading staticfile_buildpack...  
           Downloaded dotnet_core_buildpack  
           Downloaded nodejs_buildpack  
           Downloaded staticfile_buildpack  
           Downloaded python_buildpack  
           Downloaded php_buildpack  
           Creating container  
           Successfully created container  
           Downloading app package...  
           Downloaded app package (879.7K)  
           -----> Go Buildpack version 1.8.18  
           -----> Checking Godeps/Godeps.json file  
           -----> Installing godep v80  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/godep/godep-v80-linux-x64-3b019ddc.tgz]  
           -----> Installing glide v0.13.1  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/glide/glide-v0.13.1-linux-x64-4959fbf0.tgz]  
           -----> Installing dep v0.4.1  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/dep/dep-v0.4.1-linux-x64-c678d9fc.tgz]  
           -----> Installing go 1.8.7  
                  Download [https://buildpacks.cloudfoundry.org/dependencies/go/go1.8.7.linux-amd64-2a8d24c3.tar.gz]  
           -----> Running: go install -tags cloudfoundry -buildmode pie ./...  
           Exit status 0  
           Uploading droplet, build artifacts cache...  
           Uploading build artifacts cache...  
           Uploading droplet...  
           Uploaded build artifacts cache (214B)  
           Uploaded droplet (4.8M)  
           Uploading complete  
           Stopping instance 5c45cef2-6210-4aa6-8a16-430acb9466be  
           Destroying container  
           Successfully destroyed container  
             
           0 of 1 instances running, 1 starting  
           0 of 1 instances running, 1 starting  
           0 of 1 instances running, 1 starting  
           0 of 1 instances running, 1 crashed  
           Deleting app notifications in org system / space notifications-service as admin...  
           OK  
           Renaming app notifications-venerable to notifications in org system / space notifications-service as admin...  
           OK  
           error: Error restarting application: Start unsuccessful  
             
           TIP: use 'cf logs notifications --recent' for more information  
           Deleting app notifications-venerable in org system / space notifications-service as admin...  
           OK  
           App notifications-venerable does not exist.  
           FAILED  
           Service instance notifications-logger not found  
           Syslog URL is not set.  
           Scaling app notifications in org system / space notifications-service as admin...  
           OK  
           Default template is not set.  
           Deployment failed!  
             
Stderr     + export PATH=/var/vcap/packages/notifications-cf-cli/bin:/var/vcap/packages/notifications-jq/bin:/usr/sbin:/usr/bin:/sbin:/bin  
           + PATH=/var/vcap/packages/notifications-cf-cli/bin:/var/vcap/packages/notifications-jq/bin:/usr/sbin:/usr/bin:/sbin:/bin  
           ++ mktemp -d  
           + export CF_HOME=/var/vcap/data/tmp/tmp.TW8bqkaOk1  
           + CF_HOME=/var/vcap/data/tmp/tmp.TW8bqkaOk1  
           + export CF_DIAL_TIMEOUT=5  
           + CF_DIAL_TIMEOUT=5  
           + SCHEME=https  
           + DOMAIN=cf.healthwatch.gcp.pcf-metrics.com  
           + ADMIN_USER=admin  
           + ADMIN_PASSWORD=assf2334ajkli34jkla33  
           + API_ENDPOINT=https://api.cf.healthwatch.gcp.pcf-metrics.com  
           + ORG=system  
           + SPACE=notifications-service  
           + APP_NAME=notifications  
           + APP_DOMAIN=cf.healthwatch.gcp.pcf-metrics.com  
           + DEFAULT_TEMPLATE=  
           + UAA_ADMIN_CLIENT=admin  
           + UAA_ADMIN_SECRET=jhgvp0ul0x8nuxoprt1a  
           + SYSLOG_URL=  
           + MANIFEST=/var/vcap/jobs/deploy-notifications/manifest.yml  
           + mkdir -p /var/vcap/data/tmp/tmp.TW8bqkaOk1  
           + ERROR_EXIT_CODE=1  
           + DEPLOYMENT_STATUS=0  
           + cf -v  
           + validate_database_connection_count  
           + [[ 10 -eq 0 ]]  
           + ((  10 < 2  ))  
           + validate_smtp_config  
           + warning_message='The notifications service was not deployed because SMTP host or port is missing'  
           + [[ -z smtp.sendgrid.net ]]  
           + [[ -z 2525 ]]  
           + authenticate_and_target  
           + cf api https://api.cf.healthwatch.gcp.pcf-metrics.com --skip-ssl-validation  
           + cf auth admin assf2334ajkli34jkla33  
           + cf create-org system  
           + cf target -o system  
           + cf create-space notifications-service  
           + cf target -s notifications-service  
           + create_manifest  
           + cat /var/vcap/jobs/deploy-notifications/manifest.yml  
           + cp /var/vcap/jobs/deploy-notifications/manifest.yml /var/vcap/packages/notifications/manifest.yml  
           + scale_app_down  
           + set +e  
           + cf app notifications --guid  
           + local exit_code=0  
           + set -e  
           + [[ 0 -eq 0 ]]  
           + cf scale notifications -i 1  
           + push_app  
           + local exit_code  
           + mkdir -p /var/vcap/data/tmp  
           + export TMPDIR=/var/vcap/data/tmp  
           + TMPDIR=/var/vcap/data/tmp  
           + pushd /var/vcap/packages/notifications  
           + set +e  
           + cf app notifications --guid  
           + exit_code=0  
           + set -e  
           + [[ 0 -ne 0 ]]  
           + cf install-plugin /var/vcap/packages/notifications-cf-cli/plugins/autopilot -f  
           + set +e  
           + cf zero-downtime-push notifications -f manifest.yml -p /var/vcap/packages/notifications  
           + exit_code=1  
           + set -e  
           + [[ 1 -ne 0 ]]  
           + handle_failed_blue_green_deploy  
           + DEPLOYMENT_STATUS=1  
           ++ jq -r '.["0"].state'  
           +++ cf app notifications --guid  
           ++ cf curl /v2/apps/ebace9fb-d3cf-4cc3-aade-7859fc63f7ce/stats  
           + local notifications_state=CRASHED  
           ++ jq -r '.["0"].state'  
           +++ cf app notifications-venerable --guid  
           App notifications-venerable not found  
           ++ cf curl '/v2/apps/FAILED/stats'  
           + local venerable_state=null  
           + [[ CRASHED = \D\O\W\N ]]  
           + [[ CRASHED != \D\O\W\N ]]  
           + [[ null != \D\O\W\N ]]  
           + cf delete notifications-venerable -f  
           + popd  
           + create_logging_service  
           + local LOGGER_NAME=notifications-logger  
           + set +e  
           + cf service notifications-logger --guid  
           + local exit_code=1  
           + set -e  
           + [[ -z '' ]]  
           + echo 'Syslog URL is not set.'  
           + [[ 1 -eq 0 ]]  
           + return  
           + scale_app_up  
           + cf scale notifications -i 2  
           + set_default_template  
           + [[ -z '' ]]  
           + echo 'Default template is not set.'  
           + return  
           + print_deployment_status  
           + [[ 1 != 0 ]]  
           + echo 'Deployment failed!'  
           + exit 1  
             

1 errand(s)

Errand 'deploy-notifications' completed with error (exit code 1)

Exit code 1

**Comment by joerodriguez** [comment]
@trevorwhitney It looks like the DATABASE_URL (10.0.16.10:3306) is set to the singleton blobstore, which does not appear to have a running mysql server.

**Comment by joerodriguez** [comment]
Here's our story to consume a bosh link: https://www.pivotaltracker.com/story/show/155292433
